# Tomcat
server:
  port: 9200

# Spring
spring:
  application:
    # 应用名称
    name: mall-auth
  profiles:
    # 环境配置
    active: dev
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 112121
