# spring配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 112121
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall_user?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Qwz#1201
#
## mybatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.qinweizhao.member
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*.xml
mybatis-plus:
  type-aliases-package: com.qinweizhao.user.model.entity
