spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 112121
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - ValidateCodeFilter
            - StripPrefix=1
        # 代码生成
        - id: mall-generator
          uri: lb://mall-generator
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
#        # 定时任务
#        - id: mall-job
#          predicates:
#            - Path=/schedule/**
#          filters:
#            - StripPrefix=1
        # 系统模块
        - id: mall-system
          uri: lb://mall-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: mall-file
          uri: lb://ruoyi-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /auth/register
      - /*/v2/api-docs
      - /csrf
