spring:
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - CacheRequestFilter
            - StripPrefix=1
        # 营销服务
        - id: mall-activity
          uri: lb://mall-activity
          predicates:
            - Path=/activity/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: mall-system
          uri: lb://mall-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 商品模块
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        # 用户模块
        - id: mall-user
          uri: lb://mall-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        # 仓库模块
        - id: mall-ware
          uri: lb://mall-ware
          predicates:
            - Path=/ware/**
          filters:
            - StripPrefix=1
        # 文件服务
        - id: mall-file
          uri: lb://mall-file
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        # 检索服务
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        # 代码生成
        - id: mall-generator
          uri: lb://mall-generator
          predicates:
            - Path=/code/**
          filters:
            - StripPrefix=1
# 安全配置
security:
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /system/notice
  # 不校验白名单
  ignore:
    whites:
      - /auth/logout
      - /auth/login
      - /captcha
      - /auth/register
      - /auth/oauth/token
      - /csrf
      - /favicon.ico
      - /*/app/**
# 验证码
captcha:
  enabled: true
  type: math